# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoopSicredi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoopSicredi
  pod 'SnapKit'

  target 'WoopSicrediTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble', '~> 8.0.0'
    pod 'Quick', '~> 2.1.0'
  end

  target 'WoopSicrediUITests' do
    # Pods for testing
  end

end
